name: 'Yusufs personal test wiser'
description: 'Provide a description here'
author: 'Yusuf Catchpoint'
inputs:
  milliseconds: # change this
    required: true
    description: 'input description here'
    default: 'default value if applicable'
  github-token:
    description:
      GitHub token for GitHub API requests.
    required: true
    default: ${{ github.token }}
runs:
  using: 'node16'
  main: 'dist/index.js'
